# Generated by Django 6.0.3 on 2026-03-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuariopersonalizado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='bio',
            field=models.TextField(blank=True, help_text='Descripción corta del usuario', max_length=300, null=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('guia', 'Guía'), ('admin', 'Administrador')], default='usuario', help_text='Rol del usuario en la aplicación', max_length=20, verbose_name='Rol'),
        ),
    ]
