# Generated by Django 6.0.3 on 2026-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Puntos_mensuales',
            new_name='puntos_mensuales',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono contacto de emergencia (con código país, ej: 573001234567)'),
        ),
    ]
